### PR TITLE
add support for background functions in api pages only

### PR DESCRIPTION
**Pull request by lindsaylevine**
Fixes https://github.com/netlify/next-on-netlify/issues/166

want to get a range of eyes on this. there is a small risk mentioned in a comment inside regarding users possibly unknowingly creating background functions if theyre not familiar with them and happen to end their api page name in background. this was an ask by one specific user awhile ago and i think, as long as there's no real risk, this would be a great offering. 

for now, i'm omitting an addition to the README documenting this support with a personal task to add it later. would like to run this by docs as well.

### CODE REVIEW

**Review by FinnWoelm — APPROVED** [review]
This looks great, @lindsaylevine! Very nice regex 😊

I agree with you that the risk of accidental background function seems rather minimal.

One small caveat is that you can't have a background function with dynamic routing (e.g., `api/[id]` or `api/[...params]`). But I don't have a good idea/fix for this and I believe no one has asked for this, so perhaps it's OK for that to not be possible for the time being?

(As a workaround, one can always create a dynamic API endpoint in addition to a non-dynamic background API endpoint and internally proxy from the former to the latter, converting path parameters into query parameters in the process (`/:id` to `?id=:id`).)

**Review by erezrokah — APPROVED** [review]
This looks good to me.
Per the risk we could add a summary - `created x routes, y functions, z background functions` or something similar (or event just print `detect the following background functions`) to make it more visible.

**Comment by sameeranand1** [comment]
Any ideas on when this might be published? Very useful and much needed feature!

**Comment by lindsaylevine** [comment]
@sameeranand1 merging now, can release shortly !

**Comment by lindsaylevine** [comment]
NoN was just released, individually. note though, if you're using the plugin, this will not be released immediately with the updated NoN version, unless necessary/requested.

**Comment by sameeranand1** [comment]
> NoN was just released, individually. note though, if you're using the plugin, this will not be released immediately with the updated NoN version, unless necessary/requested.

Thanks! I’m using the node package - it’s in that release though, right? When you’re talking about the plug-in, you’re talking about through Netlify, right? Thanks!

**Comment by lindsaylevine** [comment]
@sameeranand1 ah, yes, sorry for not being more specific! if you have `next-on-netlify` the package installed via npm or yarn, you're good to go now with v2.9.0. however, next-on-netlify will soon be fully absorbed by  https://github.com/netlify/netlify-plugin-nextjs, which is basically the exact same as `next-on-netlify`, but is zero config/one-click installable at the moment and eventually will be auto-installed on all new next.js sites on netlify. to use that plugin, you'd follow the instructions in the plugin's README :). for now, though, you're free to keep using next-on-netlify as is!

**Comment by colinwirt** [comment]
> Very nice regex 😊

Thanks @FinnWoelm! I look forward to contributing further to the project :)

Thanks for applying the change from my PR @lindsaylevine -- I updated my fork to require the path to include `next_api_` after first adding an argument as you have done, but decided that was not necessary.

I'll add a few more tests and submit another PR.

Thanks again for adding the feature so quickly.

**Comment by lindsaylevine** [comment]
@colinwirt absolutely! and yes, i shouldve noted the regex was/is 100% the work of colin! looking forward to see what you contribute next :)

**Pull request merged**
