### PR TITLE
Copy host property from headers to multiValueHeaders

### LINKED ISSUE #40: req.headers.host is undefined on netlify deployment
I'm trying to read the host in getServerSideProps. It works in local environment with 
next dev (obviously) 
next build && netlify dev

However when deployed on netlify with this plugin, 
req.headers.host is undefined. Any info on this? Thank you.

### PR DESCRIPTION
**Pull request by leomeneguzzi**
Hi everyone, looking for a solution to to resolve #40 I did my fork, and case this is acceptable in the project, I will let my PR :smile: 

This PR takes the host property from `event.headers` and copy to host in `event.multiValueHeaders`.
I'm opening this PR just in case you think this a good way to solve this problem.

PS: If you think that has another way, just give the suggest and I will take a look and implement.
PS: I don't know if this change specifically needs some test, if need, what exactly I can test.

### CODE REVIEW

**Comment by FinnWoelm** [comment]
This is perfect, @leomeneguzzi! :raised_hands: We will merge this as soon as possible!

**Comment by s-kris** [comment]
@FinnWoelm It looks like the PR is missing a label and that caused the tests to fail. Can you look into this?

**Comment by lindsaylevine** [comment]
@s-kris @leomeneguzzi i'll get this taken care of asap!

**Comment by abdelhamid-attaby** [comment]
@lindsaylevine could we merge this and publish it? It is very crucial to us.

**Review by cassidoo — APPROVED** [review]
Let's merge this and make a note to remove it when it is fixed internally!

**Comment by lindsaylevine** [comment]
closing because of conflict in favor of https://github.com/netlify/next-on-netlify/pull/44 and getting out asap

**Comment by lindsaylevine** [comment]
@s-kris @leomeneguzzi @abdelhamid-attaby this was just published!

**Comment by abdelhamid-attaby** [comment]
Thanks @lindsaylevine but I opened a same issue with `x-forwarded-host` header. Please check #46

**Pull request closed without merging**
