### PR TITLE
Add tests Pt. 1

### PR DESCRIPTION
**Pull request by BrandonKlotz**
## Add Tests Pt. 1

Started adding tests and was finding we `require` certain packages/modules we don't use so removed unused requires.
- This seemed to help speed up running tests a little.
- This led me to notice areas in the code outside of tests we have require but don't use, so removed those as well. 

Added tests for some things I understood, which led me to better understand a bit more 😂 :
- [x] isApiRoute
- [x] isHtmlFile
- [x] isFrameworkRoute

This gave me a better understanding of how `getPagesManifest` is working so that will be my starting point in `add-tests-pt2`.

It'd also be cool to add CI testing statuses badge for the `main` branch and possibly per commit via something like TravisCI.

### CODE REVIEW

**Comment by FinnWoelm** [comment]
Hey @BrandonKlotz, wow, this is really neat! 🤩

I need to take a closer look later this week (hopefully), but at first glance, it looks great and very clear! I really like this. Unit tests have always been on the to-do list 📝

Thank you!! 🙌🙌🙌

**Comment by BrandonKlotz** [comment]
Hey @FinnWoelm just wanted to check in and see if there was anything here I could improve 😀, sorry for the late response here the last couple weeks have been a time well.

**Comment by lindsaylevine** [comment]
@BrandonKlotz hey brandon! so sorry we've neglected this. we've been super busy 😫 but i still super appreciate this work!

main question: is there a use-case for the helpers you added? the tests are great but i don't know if we should commit helpers before they're being used anywhere

**Comment by BrandonKlotz** [comment]
Hey sorry for also unintentionally abandoning this PR, your right we probably shouldn't add unused helper methods, I think I accidentally pulled them over from a PR idea I had for supporting the trigger event function, thanks for closing this out 👍

**Comment by lindsaylevine** [comment]
no worries!!! we can always revisit later if we find a use for it :)

**Pull request closed without merging**
