### PR TITLE
Allow function filenames to end in -background

### PR DESCRIPTION
**Pull request by colinwirt**
Support Netlify background functions

### CODE REVIEW

**Comment by colinwirt** [comment]
This is the feature announcement https://www.netlify.com/blog/2020/10/29/announcing-background-functions/

As far as I know, the only way to create a background function is by appending `-background` to the end of the filename, therefore the existing regex will never allow a background function to be created.

There may be better ways to support this via next, such as a background function interface or a specific method name in the api route page perhaps?

**Comment by colinwirt** [comment]
@FinnWoelm I was wondering if simply allowing function names to include dashes would be a cleaner solution.

**Comment by colinwirt** [comment]
Hey @lindsaylevine @FinnWoelm @cassidoo, I was wondering if you could give some feedback about background functions and tag this PR for me :)

**Comment by lindsaylevine** [comment]
@colinwirt hey colin! sorry, we're all coming off the holidays and swamped with a bunch of other things!

are you using the plugin right now and trying to use your own custom functions, including the new background functions? custom netlify functions (aka functions you write yourself) are only supported in our [plugin](https://github.com/netlify/netlify-plugin-nextjs). if that's the case, next-on-netlify should not be messing with your custom function names at all. the file you changed is intended to generate a file name for the next.js page types that require a netlify function, so changing that regex will only pay attention to next.js page names (i.e. pages/api/some-page-name.js or pages/ssr/my-ssr-page.js).

also, next-on-netlify only wants to use standard netlify functions for these page types (we don't want to pivot to creating background functions where we have always used normal functions). 

does that make sense? let me know!

**Comment by colinwirt** [comment]
> are you using the plugin right now and trying to use your own custom functions, including the new background functions?

@lindsaylevine Yes. we're building out a site using the plugin -- posting a form to our api route `pages/api/contact-us.js`.

After building the contact us endpoint it turns out the work that form handler needs to do takes 12-14 seconds hitting a dev version of ticket management services, which is what lead me to experiment with getting that api to kick-off a background task.

> also, next-on-netlify only wants to use standard netlify functions for these page types (we don't want to pivot to creating background functions where we have always used normal functions).

I realise I may have come the long way around to making a custom netlify function, is there a way I can get the plugin to find a custom background function outside the `pages` and `pages/api` path and copy that into the `functions` path?

**Comment by colinwirt** [comment]
I managed to get this to work on Netlify with the route `/api/contact-us-background` using my own npm package with this change applied.

Would you consider allowing the user to decide whether an api route should run in the background, rather than never supporting the feature?

**Comment by lindsaylevine** [comment]
@colinwirt 

>I realise I may have come the long way around to making a custom netlify function, is there a way I can get the plugin to find a custom background function outside the pages and pages/api path and copy that into the functions path? (I suppose I can do that myself with webpack!)

yes, if you're using the plugin, you can set a custom functions dir in `netlify.toml` (see the README). let's say you set it to `my-functions`. then you can put contact-us-background.js in `my-functions`, and the plugin will put all NoN-generated functions in `my-functions` *alongside* `contact-us-background.js` and any other custom functions you may want.

>Would you consider allowing the user to decide whether an api route should run in the background, rather than never supporting the feature?

need to think a bit more about any tradeoffs or implications of doing so, use cases (like yours!), and how we might implement that. if that's something you think we should definitely add in place of the custom function solution i gave, can you open an issue in this repo p pls that specifically asks for the ability to turn certain `api` pages/routes into background functions? 🙏

**Pull request closed without merging**
